name: Branch Pruning

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day

jobs:
  prune_branches:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Prune branches older than 30 days
        run: |
          git fetch --prune
          git branch --merged origin/main | grep -v 'main$' | xargs -n 1 git branch -d
